### ISSUE TITLE
Is this replacing astroconda-dms-hst?

### ISSUE THREAD

**Issue by sosey** [astroconda/astroconda-releases#2]
@jhunkeler  Have we moved to using this astroconda-releases repo instead of or in addition to the astroconda-dms-hst and astroconda-dms-jwst repositories we started with? They have similar content, I just want to be clear which should be used.

**Comment by jhunkeler** [comment]
Ack, yes this one! Sorry @sosey... I don't know how I didn't see this issue before today.

😞
